### ISSUE TITLE
`vehicle-rental-overlay` can not be imported directly

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [opentripplanner/otp-ui#266]
`vehicle-rental-overlay` imports `base-map`. Unfortunately, it does so in peer dependencies. If you try to import `vehicle-rental-overlay` directly (using the directory or by copying the built files into a project like otp-rr) things fail miserably (the UI crashes white screen). 

If you move the base map dependency to the "regular" dependencies, everything works perfectly.

**Comment by evansiroky** [comment]
This is expected behavior in order to maintain package consistency. If each package that uses the `base-map` package defines it as a regular dependency, then this opens the door to potentially multiple different versions of `base-map` which causes other problems. The solution to this issue is to make sure that only one version of `base-map` is used in the implementing project. If an newer version is needed, it is the responsibility of the implementing project to update to the desired version. This also applies to other packages like `react` and `styled-components`.
