### ISSUE TITLE
Transitive Overlay rendering is inaccurate without intermediate stops

### ISSUE THREAD

**Issue by randolphjones** [opentripplanner/otp-ui#47]
When rendering an itinerary without intermediate stops, the transitive overlay looks to be inaccurate. It looks like it only renders the geometry between the last two stops on each leg. 

With intermediate stops:
![image](https://user-images.githubusercontent.com/5219049/73116058-045f2a80-3ee5-11ea-81bb-151ee1a7a023.png)
Without:
![image](https://user-images.githubusercontent.com/5219049/73116080-5ef88680-3ee5-11ea-80fc-c73faba28faf.png)

**Comment by fpurcell** [comment]
See #42 and #36

**Comment by randolphjones** [comment]
To clarify, I am seeing this issue with both `core-utils` and `transitive-overlay` on v `0.0.12`

**Comment by evansiroky** [comment]
This bug report is what I deserve for not testing with data that actually came from OTP.

**Comment by evansiroky** [comment]
FYI, the otp-react-redux application will always make requests for the intermediate stops as they are used in the ItineraryBody component to show how many stops a user has to ride. These stops are also displayed when a user clicks the DefaultTransitLegSummary component to toggle the view of stops. In otp-react-redux these intermediate stops are also rendered as a schematic element within the transit line display.

<img width="541" alt="Screen Shot 2020-01-26 at 10 29 38 AM" src="https://user-images.githubusercontent.com/3112493/73139865-55773780-4027-11ea-9b54-fc8a88de8820.png">

The design of otp-react-redux attempts to make the line/stops display in the itinerary body consistent with what is shown on the map in the transitive overlay. I'm not sure if this current design really needs those intermediate stops showing up in the line display so thought I'd bring this up since this functionality might be more suited for just the otp-react-redux implementation.

**Comment by randolphjones** [comment]
Thanks. That all makes sense. I'm ok with us always making the request with intermediate stops as well. @fpurcell may have a strong preference here when it comes to how he wants the app we're building to function. At a glance it looks like we want it to operate the same way as OTP-RR.
